# Generated by Django 5.1.5 on 2025-01-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_personalinfo_about_me_personalinfo_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(choices=[('Personal Information', 'Personal Information'), ('Project', 'Project'), ('Experience', 'Experience'), ('Education', 'Education'), ('Certification', 'Certification'), ('Skills', 'Skills'), ('Technology', 'Technology')], max_length=200)),
            ],
        ),
    ]
