# Generated by Django 5.1.5 on 2025-01-19 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_personalinfo_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='name',
            new_name='f_name',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='l_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
